### ISSUE TITLE
Issues with networks 2.4 in cirq-core

### ISSUE THREAD

**Issue by cqc-melf** [CQCL/pytket-cirq#25]
cirq-core is currently not compatible with pytket because of the requirement of  networks 2.4.

See https://github.com/quantumlib/Cirq/issues/6047

**Comment by cqc-melf** [comment]
Can we test that this is now working with 3.x with the new dev release from cirq before closing this? @cqc-alec

**Comment by cqc-melf** [comment]
Can we test that this is now working with 3.x with the new dev release from cirq before closing this? @cqc-alec

**Comment by cqc-alec** [comment]
Good point, I have tested this locally by installing pytket-cirq (which pulls in networkx 2.8), then manually installing networkx 3.1, and then running the pytket-cirq tests; they all passed.

**Comment by cqc-melf** [comment]
Great!
